stages:
  - install
  - checks

install:
  stage: install
  image: node:16
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 2 hour

codestyle:
  stage: checks
  image: node:16
  needs:
    - install
  dependencies:
    - install
  allow_failure: true
  script:
    - npm run codestyle

tests:
  stage: checks
  image: node:16
  needs:
    - install
  dependencies:
    - install
  script:
    - npm run test
