version: "3.8"
services:
  ads-sample:
    image: node:16
    volumes:
      - ./:/var/www/
    working_dir: /var/www
    ports:
      - 3300:3300
      - 9229:9229

    depends_on:
      - mongo
    environment:
      MONGO_DSN: mongodb://mongo/ads-framework
    command: "npm run docker"

  mongo:
    image: mongo:4.4-bionic
    volumes:
      - mongodata:/data/db
      - ./dump:/dump
    ports:
      - 27017:27017

volumes:
  mongodata:
    driver: local
