services:
  backend:
    image: registry.gitlab.com/adaptivestone/ubuntu-node:latest
    volumes:
      - ./:/var/www/
    working_dir: /var/www
    ports:
      - 3300:3300
      - 9229:9229

    depends_on:
      - mongo
      - redis
    environment:
      MONGO_DSN: mongodb://mongo/ads-framework?replicaSet=rs0
      REDIS_URI: redis://redis
      EMAIL_HOST: mailcatcher
      EMAIL_PORT: 1025
    command: "npm run docker"

  mongo:
    image: mongo:8.0
    volumes:
      - mongodata:/data/db
      - ./dump:/dump
    ports:
      - 27017:27017
    entrypoint:
      [
        '/usr/bin/mongod',
        '--bind_ip_all',
        '--wiredTigerCacheSizeGB',
        '1',
        '--replSet',
        'rs0'
      ]
    healthcheck:
      test: test $$(mongosh --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      retries: 5

  redis:
    image: redis
    ports:
      - 6379:6379

  # dev to check email
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - 1080:1080

volumes:
  mongodata:
    driver: local
