import AbstractController from '@adaptivestone/framework/modules/AbstractController.js';
import Mailer from '@adaptivestone/framework-module-email';
import type { Response } from 'express';
import { z } from 'zod';
// Generated by `npm run gen`; the `params:` schema below types
// `req.appInfo.params.email`, while raw `req.params.email` stays a string.
import type { GetEmailRequest } from './Email.routes.gen.ts';

class Email extends AbstractController {
  get routes() {
    return {
      get: {
        '/:email': {
          handler: this.getEmail,
          // A path param is an input like any other — validate it. A bad
          // address never reaches the mailer.
          params: z.object({ email: z.email() }),
        },
      },
    };
  }

  async getEmail(req: GetEmailRequest, res: Response) {
    // Address shape is guaranteed by the route's `params:` schema above.
    // This route exists to exercise mail delivery; it is not production ready.
    const mail = new Mailer(
      req.appInfo.app,
      req.appInfo.params.email,
      req.query,
      req.appInfo.i18n,
    );
    const result = await mail.send('test@mail.com');
    return res.status(200).json(result);
  }

  static get middleware() {
    return new Map([['/{*splat}', []]]);
  }
}

export default Email;
