import AbstractController from '@adaptivestone/framework/modules/AbstractController.js';
import Mailer from '@adaptivestone/framework-module-email';
import type { Response } from 'express';
// Generated by `npm run gen`; `:email` is typed as `req.params.email: string`.
import type { GetEmailRequest } from './Email.routes.gen.ts';

class Email extends AbstractController {
  get routes() {
    return {
      get: {
        '/:email': {
          handler: this.getEmail,
        },
      },
    };
  }

  async getEmail(req: GetEmailRequest, res: Response) {
    // TODO error check, pass params check. This is just for testing emails, not production ready
    const mail = new Mailer(
      req.appInfo.app,
      req.params.email,
      req.query,
      req.appInfo.i18n,
    );
    const result = await mail.send('test@mail.com');
    return res.status(200).json(result);
  }

  static get middleware() {
    return new Map([['/{*splat}', []]]);
  }
}

export default Email;
