import AbstractController from '@adaptivestone/framework/modules/AbstractController.js';
import type { Response } from 'express';
// Generated by `npm run gen` from this controller's `routes` getter.
// Handler request types (typed `appInfo`, `params`, `query`, body) come from here.
import type { GetPersonRequest } from './Person.routes.gen.ts';

class Person extends AbstractController {
  get routes() {
    return {
      get: {
        '/': {
          handler: this.getPerson,
        },
      },
    };
  }

  async getPerson(req: GetPersonRequest, res: Response) {
    // `getModel('Person')` is typed via the generated `genTypes.d.ts` — no cast.
    const PersonModel = req.appInfo.app.getModel('Person');
    let person = await PersonModel.findOne({ lastName: 'Show' });

    if (!person) {
      // just for demo
      person = await PersonModel.create({
        firstName: 'Jon',
        lastName: 'Snow',
      });
    }
    try {
      await person.sendCreatEmail(req.appInfo.i18n);
    } catch (e) {
      if (e instanceof Error) {
        this.logger?.error(e.message);
      } else {
        this.logger?.error('An unknown error occurred');
      }
    }
    return res.status(200).json(person);
  }

  static get middleware() {
    return new Map([['/{*splat}', []]]);
  }
}

export default Person;
