import { getAppInstance } from '@adaptivestone/framework/helpers/appInstance.js';
import AbstractController from '@adaptivestone/framework/modules/AbstractController.js';
import { NotFoundError } from '@adaptivestone/framework/services/http/httpErrors.js';
import RateLimiter from '@adaptivestone/framework/services/http/middleware/RateLimiter.js';
import type { Response } from 'express';
import { z } from 'zod';
// Generated by `npm run gen` from this controller's `routes` getter.
// Handler request types (typed `appInfo`, `params`, `query`, body) come from here.
import type {
  CreatePersonRequest,
  GetPersonByIdRequest,
  GetPersonRequest,
} from './Person.routes.gen.ts';

// Config is fully merged before controller modules load. Generated config types
// preserve this policy name, so a typo fails `npm run check:types`.
const { policy } = getAppInstance().getConfig('rateLimiter');

class Person extends AbstractController {
  get routes() {
    return {
      get: {
        '/': {
          handler: this.getPerson,
        },
        '/:id': {
          handler: this.getPersonById,
        },
      },
      post: {
        '/': {
          handler: this.createPerson,
          // Any Standard Schema validator works as a route schema. The schema's
          // inferred output becomes the typed `req.appInfo.request` (see handler).
          request: z.object({
            firstName: z.string(),
            lastName: z.string(),
          }),
        },
      },
    };
  }

  // POST /person — request body is validated and typed by the schema above.
  async createPerson(req: CreatePersonRequest, res: Response) {
    const { firstName, lastName } = req.appInfo.request;
    const PersonModel = req.appInfo.app.getModel('Person');
    const person = await PersonModel.create({ firstName, lastName });
    return res.status(201).json({ data: person });
  }

  // GET /person/:id — demonstrates typed HTTP errors (framework ≥ 5.1).
  // Thrown `HttpError`s resolve to their status through the error-handler
  // registry, so any depth of business logic can end a request cleanly
  // without threading `res` around. See docs: Controllers → Error handling.
  async getPersonById(req: GetPersonByIdRequest, res: Response) {
    const { id } = req.params;
    const PersonModel = req.appInfo.app.getModel('Person');
    // Path params arrive as raw strings — guard the ObjectId shape before
    // Mongoose, or a malformed id becomes a CastError → 500
    // (see docs: Recipes → Validate an ObjectId).
    const person = /^[0-9a-fA-F]{24}$/.test(id)
      ? await PersonModel.findById(id)
      : null;
    if (!person) {
      throw new NotFoundError('Person not found');
      // → 404 { "message": "Person not found" }
    }
    return res.status(200).json({ data: person });
  }

  async getPerson(req: GetPersonRequest, res: Response) {
    // `getModel('Person')` is typed via the generated `genTypes.d.ts` — no cast.
    const PersonModel = req.appInfo.app.getModel('Person');
    let person = await PersonModel.findOne({ lastName: 'Show' });

    if (!person) {
      // just for demo
      person = await PersonModel.create({
        firstName: 'Jon',
        lastName: 'Snow',
      });
    }
    try {
      await person.sendCreatEmail(req.appInfo.i18n);
    } catch (e) {
      if (e instanceof Error) {
        this.logger?.error(e.message);
      } else {
        this.logger?.error('An unknown error occurred');
      }
    }
    return res.status(200).json(person);
  }

  static get middleware() {
    return new Map([
      ['/{*splat}', []],
      ['POST/', [[RateLimiter, policy.personCreate] as const]],
    ]);
  }
}

export default Person;
