import AbstractController from '@adaptivestone/framework/modules/AbstractController.js';
import Auth from '@adaptivestone/framework/services/http/middleware/Auth.js';
import GetUserByToken from '@adaptivestone/framework/services/http/middleware/GetUserByToken.js';
import type { Response } from 'express';
// Generated by `npm run gen`. Because this controller runs behind
// `[GetUserByToken, Auth]`, the generated type makes `req.appInfo.user` the
// authenticated (non-null) user document — no `if (!user)` guard needed.
import type { GetProfileRequest } from './Profile.routes.gen.ts';

class Profile extends AbstractController {
  get routes() {
    return {
      get: {
        '/': {
          handler: this.getProfile,
        },
      },
    };
  }

  // Returns the currently authenticated user.
  async getProfile(req: GetProfileRequest, res: Response) {
    return res.status(200).json({ data: await req.appInfo.user.getPublic() });
  }

  // `[GetUserByToken, Auth]` requires a valid auth token on every route here.
  // (It is also AbstractController's default chain — shown explicitly for the
  // example. Use an empty `[]` array, like Person/Email, to make routes public.)
  static get middleware() {
    return new Map([['/{*splat}', [GetUserByToken, Auth]]]);
  }
}

export default Profile;
